spring:
  zipkin:
    base-url: http://localhost:9411/
  config:
    import: configserver:http://localhost:9196
  application:
    name: PAYMENT-SERVICE
logging:
  file: 
    name: C:/Users/Zaid/Desktop/logs/microservice.log